/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BoxComponent: typeof import('./src/components/home/BoxComponent.vue')['default']
    BoxContent: typeof import('./src/components/home/BoxContent.vue')['default']
    CollectionBox: typeof import('./src/components/collection/CollectionBox.vue')['default']
    DefaultValue: typeof import('./src/components/uploader/DefaultValue.vue')['default']
    DetailsMain: typeof import('./src/components/details/DetailsMain.vue')['default']
    DetailsTitle: typeof import('./src/components/details/DetailsTitle.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElText: typeof import('element-plus/es')['ElText']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FilterBoxComponent: typeof import('./src/components/filter/FilterBoxComponent.vue')['default']
    FilterBoxContent: typeof import('./src/components/filter/FilterBoxContent.vue')['default']
    FilterPanel: typeof import('./src/components/common/FilterPanel.vue')['default']
    FooterBar: typeof import('./src/components/common/FooterBar.vue')['default']
    GridItem: typeof import('./src/components/grid/GridItem.vue')['default']
    GridRow: typeof import('./src/components/grid/GridRow.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MenuPanel: typeof import('./src/components/common/MenuPanel.vue')['default']
    NavBar: typeof import('./src/components/common/NavBar.vue')['default']
    PhonePanel: typeof import('./src/components/common/PhonePanel.vue')['default']
    PostEditorMain: typeof import('./src/components/post_information/PostEditorMain.vue')['default']
    PostImage: typeof import('./src/components/post_information/PostImage.vue')['default']
    PostInformationMain: typeof import('./src/components/post_information/PostInformationMain.vue')['default']
    QuicklyJumpBar: typeof import('./src/components/common/QuicklyJumpBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchComponent: typeof import('./src/components/search/SearchComponent.vue')['default']
    SearchInput: typeof import('./src/components/common/SearchInput.vue')['default']
    TypeSelector: typeof import('./src/components/uploader/TypeSelector.vue')['default']
    UploadImage: typeof import('./src/components/uploader/UploadImage.vue')['default']
    VerticalMenu: typeof import('./src/components/grid/VerticalMenu.vue')['default']
  }
}
